
name: Crear rama de changelog

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  create-upload-changelog-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout completo del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generar sección de CHANGELOG
        run: |
          echo "## $(date +'%Y-%m-%d')" >> CHANGELOG.md
          git log ${{ github.event.before }}..${{ github.sha }} \
            --pretty=format:"- %s" >> CHANGELOG.md

      - name: Crear o resetear rama uploadchangelog
        run: git checkout -B uploadchangelog

      - name: Configurar autor del commit
        run: |
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"

      - name: Commit de los cambios con mensaje del último push
        run: |
          git add CHANGELOG.md
          git commit -m "${{ github.event.head_commit.message }}"

      - name: Push de la rama uploadchangelog
        run: git push --force --set-upstream origin uploadchangelog
