# .github/workflows/changelog-local-update.yml
name: Local Changelog Prep

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prepare-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Create new branch and update changelog
        run: |
          BRANCH="changelog-temp-$(date +%s)"
          git checkout -b $BRANCH
          echo "## Cambios en $(date '+%Y-%m-%d')" > changelog_temp.md
          git log -1 --pretty=format:"- %s (%h)" >> changelog_temp.md
          cat changelog_temp.md >> CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
