name: Actualizar CHANGELOG

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # necesitamos historial completo
          # persist-credentials: true  # por defecto está en true

      - name: Añadir commits recientes al CHANGELOG
        run: |
          echo "## $(date +'%Y-%m-%d')" >> CHANGELOG.md
          git log ${{ github.event.before }}..${{ github.sha }} \
            --pretty=format:"- %s" >> CHANGELOG.md

      - name: Commit y push de CHANGELOG.md como quien hizo el merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"
          git add CHANGELOG.md
          git commit -m "docs: actualizar CHANGELOG con nuevos commits"
          git push
