# .github/workflows/update-changelog.yml
name: Actualizar CHANGELOG

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ main ]

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout completo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generar sección de CHANGELOG
        run: |
          echo "## $(date +'%Y-%m-%d')" >> CHANGELOG.md
          git log ${{ github.event.before }}..${{ github.sha }} \
            --pretty=format:"- %s" >> CHANGELOG.md

      - name: Crear Pull Request con los cambios
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-changelog-${{ github.run_id }}
          base: main
          
          commit-message: "docs: actualizar CHANGELOG con nuevos commits"
          title: "docs: actualizar CHANGELOG"
          body: |
            Este PR actualiza el CHANGELOG con los commits recientes en `main`.
          author: ${{ github.event.pusher.name }} <${{ github.event.pusher.email }}>
          labels: changelog
